### ISSUE TITLE
Add SpryCss

### ISSUE THREAD

**Issue by ggedde** [troxler/awesome-css-frameworks#106]
Just wanted to check to see if you might be interested in [SpryCss](https://github.com/ggedde/spry-css)
One nice feature is that it is easy to manage unneeded breakpoints, colors, sizing options through the Sass Maps in the variables file. Which intern reduces or increases the package size based on your needs. By default it comes with 3 breakpoints, but for most of my projects I only use 2 and I don't use all the colors which brings the package size down to 9kb gzipped.

**Comment by troxler** [comment]
Thanks for the suggestion. Currently, your framework does not seem to be that popular yet. But that is a requirement as per our contribution guidelines. From a quick look, I found your focus styling on form elements somewhat lacking. The element in focus is not always clearly visible. Please try to make your framework more awesome and more popular.

**Comment by ggedde** [comment]
Thanks for the consideration and suggestions.
I will be sure to post back when ready.
