### ISSUE TITLE
Stylify CSS

### ISSUE THREAD

**Issue by Machy8** [troxler/awesome-css-frameworks#107]
Hi, please, could you add Stylify CSS? #108

**Comment by troxler** [comment]
Duplicate of #108.

**Comment by Machy8** [comment]
Hi. Sorry about that. I created an issue before the pull. Then I realized that the issue template you have is probably for the pull request so I created a pull request and linked it with this issue.

**Comment by troxler** [comment]
No worries :) I just did some cleaning up.
