### ISSUE TITLE
Shoelace.style

### ISSUE THREAD

**Issue by XeroxDev** [troxler/awesome-css-frameworks#113]
I would want to "nominate" [shoelace.style](https://shoelace.style/).
It has on github 8k stars, and has (IMO) a nice style.
AFAIK it's even partnered now with fontawesome.

Edit: I should mention it's a web component library (with custom elements), so I don't know if it counts on here. But there's a class-less category here as well, that would be the best spot I guess.

**Comment by troxler** [comment]
Thanks for the suggestion. Shoelace is indeed in another tooling category than all the other frameworks in this list. Hence, it currently does not match the list's focus.
