### ISSUE TITLE
Active spectre fork

### ISSUE THREAD

**Issue by 8ctopus** [troxler/awesome-css-frameworks#119]
[The spectre official repository is dead](https://github.com/troxler/awesome-css-frameworks/issues/82), however there is an actively maintained fork: https://github.com/angular-package/spectre.css which was updated 4 days ago in the 1.0.x branch [https://github.com/angular-package/spectre.css/tree/1.0.x](https://github.com/angular-package/spectre.css/tree/1.0.x).
I'm no css specialist but it seems to work without angular too. Maybe it's worth mentioning it?

**Comment by troxler** [comment]
Thanks for the suggestion. The project still seems very much unknown and barely anyone is using it (according to GitHub stars and npm statistics). Having a certain popularity is required to be considered for this list, though.

**Comment by 8ctopus** [comment]
Thank you for taking the time to reply, I understand your reservations. Let's hope the project grows and it can be included in the future.
