### ISSUE TITLE
Add beer.css

### ISSUE THREAD

**Issue by aolko** [troxler/awesome-css-frameworks#121]
Please add beer.css
https://github.com/beercss/beercss
https://beercss.com

**Comment by Kedarnath-Rothe** [comment]
Please assign me this issue..

**Comment by Kedarnath-Rothe** [comment]
@troxler  
What code can I add to beer.css?

**Comment by troxler** [comment]
@Kedarnath-Rothe See https://github.com/troxler/awesome-css-frameworks/blob/master/.github/CONTRIBUTING.md

**Comment by oliver3** [comment]
Hi @troxler I've created https://github.com/troxler/awesome-css-frameworks/pull/139 please have a look

**Comment by troxler** [comment]
Fixed in #139
