### ISSUE TITLE
Add a section for libs that didn't make it

### ISSUE THREAD

**Issue by n-ce** [troxler/awesome-css-frameworks#127]
I noticed there are a ton of libraries that are not being added due to standard requirements not being fulfilled while this is a good practice to keep the list clean, It does hinder discovery of such libraries, some of them are even quite popular.
So I would suggest opening up another section same as `stalled developement` but for `Not Standard Compliant` or something like that. 
No we cannot add every other css library to it so we'll have to choose an abritrary rule (such as no. of gh stars > 1k) for limiting the list.

**Comment by Kedarnath-Rothe** [comment]
Please assign me this issue

**Comment by troxler** [comment]
Thanks for the suggestion. This list is focused on **good** CSS frameworks that fulfill certain quality criteria and are at least somewhat popular. I'm not willing to spend time maintaining a list of low-quality, outdated and/or unmaintained frameworks. If you prefer quantity over quality or favour discoverability of new frameworks, maybe https://github.com/gabrielizalo/Awesome-CSS-Frameworks-and-UI-Libraries is useful to you. But in this list here, I do not see a benefit of loosening the criteria for addition.
