### ISSUE TITLE
Add microscope.css

### ISSUE THREAD

**Issue by nichdemos** [troxler/awesome-css-frameworks#136]
Hi.

Please add microscope.css - *🔬 A simple and fast Atomic Design boilerplate.*
https://github.com/afonsopacifer/microscope
https://github.com/afonsopacifer - author of microscope.css

**Comment by troxler** [comment]
Thanks for the suggestion, but this project has not seen any change in more than six years. This list only includes active projects, though.

**Comment by nichdemos** [comment]
Hi @troxler, thanks for comment here again!
