### ISSUE TITLE
can I share this project with my developer friends?

### ISSUE THREAD

**Issue by nichdemos** [troxler/awesome-css-frameworks#138]
Hi @troxler, how are you?

Can I share this project with my developer friends?  Is there any image or trademark rights in this open source project that restrict the dissemination and promotion of this project?

**Comment by troxler** [comment]
Hi. Sure, you can share this with anyone. This repository is [licensed as CC0](https://github.com/troxler/awesome-css-frameworks#license) and there are no restrictions or trademarks.

**Comment by nichdemos** [comment]
Oi @troxler, thanks for comment here!!!!
