### ISSUE TITLE
mdui

### ISSUE THREAD

**Issue by Metis77** [troxler/awesome-css-frameworks#149]
Any reason why mdui ist not on this list?
https://github.com/zdhxiong/mdui

It seams to be well accepted und in active developement.

**Comment by troxler** [comment]
Thanks for the suggestion. Unfortunaly, mdui has severe accessibility deficiencies. For example, most of their interactive components do not have a focus styling and/or are not usable from the keyboard. I would definitely not recommend using it. A way better alternative based on web components is https://github.com/shoelace-style/shoelace.
