### ISSUE TITLE
How about W3CSS?

### ISSUE THREAD

**Issue by vit1251** [troxler/awesome-css-frameworks#15]
Hello, 

How about w3css it also CSS Framework

Thanks.

**Comment by troxler** [comment]
Thanks for the suggestion. However, W3CSS has neither a code repository nor bug tracker which both is required as per the [contribution guidelines](https://github.com/troxler/awesome-css-frameworks/blob/master/.github/CONTRIBUTING.md).

**Comment by vit1251** [comment]
I found W3CSS code repositroy one https://github.com/vitorlans/w3-css

**Comment by troxler** [comment]
That looks like an unofficial repository. Also, there is no actual version history of the framework (e.g. [w3pro.css](https://github.com/vitorlans/w3-css/commits/master/4/w3pro.css)). It seems this repository is only used to add W3CSS to npm.

In order to be listed here, an *official* repository and bug tracker are required.

**Comment by vit1251** [comment]
OK. I understand you. I contact with author about official repository.

**Comment by JaniRefsnes** [comment]
Official repository at https://github.com/JaniRefsnes/w3css

**Comment by vit1251** [comment]
@JaniRefsnes could I ask you add link on website os GIT repository and write a few words about how to use in CSS packager tools on w3css. I use Python and Golang as backend platform.

**Comment by troxler** [comment]
@vit1251 Thanks for the effort.

@JaniRefsnes Thanks for stepping in. Although this is described as the official repository, it does not actually have any version history (yet). The point of having a requirement on a repository is to ensure that users can follow the actual development and see exactly what changed between versions. The current code in the repository looks like a nearly-minified dump but not as a code base where actual development happens. And I did not find any mention of the repository on the W3.CSS website at all. Can you please add a link?
