### ISSUE TITLE
Add Bourbon?

### ISSUE THREAD

**Issue by vaz** [troxler/awesome-css-frameworks#19]
Hey, what about [https://www.bourbon.io](Bourbon)?

I realize it's actually entirely a Sass library (it doesn't come with, or output, any CSS by default but provides Sass functions and mixins), but maybe it still qualifies.

Also in the Bourbon family: [Neat](https://neat.bourbon.io) (Sass-based grid), [Bitters](http://bitters.bourbon.io) (Bourbon-based scaffolding with some default styles - since on its own Bourbon has no visual opinions).

**Comment by troxler** [comment]
Thanks for the suggestion :)
