### ISSUE TITLE
Add the Ink Framework

### ISSUE THREAD

**Issue by WhitewaterDave** [troxler/awesome-css-frameworks#23]
Ink is an interface kit for quick development of web interfaces, simple to use and expand on. It uses a combination of HTML, CSS and JavaScript to offer modern solutions for building layouts, display common interface elements and implement interactive features that are content-centric and user friendly for both your audience and your designers & developers. Ink is part of SAPO's Open Source Software initiative.

Their website is [http://ink.sapo.pt/](http://ink.sapo.pt/).

**Comment by troxler** [comment]
Ink seems to have been abandoned. Therefore, I do not think it is a good addition to the list.

If you think it should be added after all, please create a pull requestion and add it to the "Stalled Development" section.
