### ISSUE TITLE
NES.css Framework

### ISSUE THREAD

**Issue by lalaithan** [troxler/awesome-css-frameworks#25]
[Homepage](https://nostalgic-css.github.io/NES.css/)
[Github page](https://github.com/nostalgic-css/NES.css)

**Comment by troxler** [comment]
Could you please create a [pull request](https://github.com/troxler/awesome-css-frameworks/blob/master/.github/CONTRIBUTING.md)?

**Comment by lalaithan** [comment]
@troxler Should it go under "Specialized"?

**Comment by troxler** [comment]
Yes, I think that is the most suitable section for it.
