### ISSUE TITLE
Other lightweight CSS frameworks

### ISSUE THREAD

**Issue by DonaldTsang** [troxler/awesome-css-frameworks#31]
- https://tutorialzine.com/2018/05/10-lightweight-css-frameworks-you-should-know-about
- https://dzone.com/articles/top-10-lightweight-css-frameworks-for-building-fas
- https://www.catswhocode.com/blog/top-10-lightweight-css-frameworks-for-building-fast-websites-in-2018
- http://www.creativeweblogix.com/blog/12-lightweight-css-frameworks
- https://speckyboy.com/responsive-lightweight-css-frameworks/

**Comment by troxler** [comment]
I looked through those links. Most frameworks are either gone, outdated, or not used by anybody.

Here is a list of frameworks that might comply with this repo's rules:

* https://github.com/avalanchesass/avalanche
* https://github.com/canonical-web-and-design/vanilla-framework
* https://github.com/daemonite/material
* https://github.com/Dogfalo/materialize
* https://github.com/FezVrasta/bootstrap-material-design
* https://github.com/kylelogue/mustard-ui
* https://github.com/lumapps/lumX
* https://github.com/siimple/siimple
* https://github.com/sitetent/tentcss
* https://github.com/sujan-s/fictoan

**Comment by DonaldTsang** [comment]
@troxler some of the repo's "lightweight" frameworks are also outdated for at least a year or more, might want to double check

**Comment by animachristi** [comment]
This one https://mincss.com/
But I think it's outdated? I don't know. I use it in my website.
Many thanks for the list, good job to everyone.

**Comment by DonaldTsang** [comment]
@animachristi it is slightly stale, so dunno if this is good or not

**Comment by troxler** [comment]
Yes this looks highly outdated. There are already many other lightweight frameworks in the list in case you are looking to replace it.

**Comment by DonaldTsang** [comment]
Is it possible to add gzipped file size for these repos?

**Comment by ZoiloGranda** [comment]
I'm using this one on a side project, looks nice and has been updated recently https://github.com/rough-stuff/wired-elements

**Comment by troxler** [comment]
@ZoiloGranda Thanks for the suggestion. But that is a component library, not a CSS framework.

**Comment by camillo777** [comment]
Nice minimal framework:

https://picocss.com/

**Comment by Tronic247** [comment]
For Material design and jQuery lovers -  https://www.tronic247.com/material/

**Comment by stgeneral** [comment]
https://picocss.com/ - Minimal CSS Framework for semantic HTML

**Comment by troxler** [comment]
Closing this as all of these frameworks seem to be either gone, outdated, or not used by anybody.

Please create *individual* issues or PRs if there are frameworks I should have a look at again.
