### ISSUE TITLE
Add gzipped size for lightweight CSS frameworks

### ISSUE THREAD

**Issue by DonaldTsang** [troxler/awesome-css-frameworks#32]
Would be useful for comparisons

**Comment by troxler** [comment]
This might be useful, but it also gets outdated very quickly as these frameworks evolve. I'm not willing to keep those numbers up-to-date.

**Comment by laurentpayot** [comment]
No need to keep it up-to-date manually. Simply add  [bundlephobia](https://badgen.net/#bundlephobia) badges like this:

- Bulma ![](https://badgen.net/bundlephobia/minzip/bulma)
- Spectre ![](https://badgen.net/bundlephobia/minzip/spectre.css)

**Comment by DonaldTsang** [comment]
@laurentpayot teach me how to do star count and bundle size badges

**Comment by laurentpayot** [comment]
Oh sorry, didn't want to be offensive. I just discovered bundlephobia recently and it's a great tool.

**Comment by laurentpayot** [comment]
@DonaldTsang it's explained at https://badgen.net/#bundlephobia

**Comment by DonaldTsang** [comment]
@troxler please reconsider this idea

**Comment by troxler** [comment]
@DonaldTsang 

> [Is it possible to add gzipped file size for these repos?](https://github.com/troxler/awesome-css-frameworks/issues/31#issuecomment-522243297)

Sure it is possible. On further reflection, I just do not think it is very useful. In almost all cases you decide on a framework based on the features that you need and not primarely on the file size.

So I do not plan on adding that information myself. But please feel free to create a pull request.

**Comment by troxler** [comment]
Closing due to lack of interest.
