### ISSUE TITLE
Paeroa CSS

### ISSUE THREAD

**Issue by t94xr** [troxler/awesome-css-frameworks#41]
- [Paeroa CSS](//t94xr.github.io/paeroa-css/)

It's new, it's a work in progress.
Would it be accepted?

**Comment by troxler** [comment]
Hello and thanks for contributing :)

Please have a look at our [contribution guidelines](https://github.com/troxler/awesome-css-frameworks/blob/master/.github/CONTRIBUTING.md). The aim of this list not to collect each and every CSS framework but only the best and/or most popular ones. So kudos to creating your own! At the moment it is not a good fit for this list (yet), though. It is still quite new and is not that popular yet.

Try to make it more mature and popular. Feel free to reopen this issue (or better yet, create a pull request) when you feel it is ready.
