### ISSUE TITLE
One more general purpose css framework

### ISSUE THREAD

**Issue by kanthvallampati** [troxler/awesome-css-frameworks#49]
There is one more framework, which is really worth to add in general purpose frameworks.

IVORY UI
Documentation - http://ivoryui.com/
GitHub Repo - https://github.com/ivory-ui/ivory

**Comment by troxler** [comment]
Thanks for contributing :) However, IVORY does not seem to be a good fit for this list yet. Its repository is still quite new, it has almost no stars and almost no downloads on npm. Aside from seemingly lacking popularity, it also has some technical flaws. The demo website has horizontal scrolling, there is no space between the screen borders and the content on smaller screens, checkboxes and radio buttons don't have a focus styling, the grid does not work properly (it breaks but does not use the available space), `pre` elements enforce scrollbars even though they might not be necessary. I think there is still some work to be done.

Thus I'm closing this for now. Feel free to add a pull request once you feel IVORY has matured and complies with this list's rules.
