### ISSUE TITLE
Add JR.css as Very Lightweight

### ISSUE THREAD

**Issue by lufemas** [troxler/awesome-css-frameworks#52]
https://lufemas.github.io/jr-css/
It has only 18kb.

![jr css](https://user-images.githubusercontent.com/5956618/87385008-1ef88f00-c56b-11ea-9a42-dfaf86f30ed3.png)

**Comment by troxler** [comment]
Thanks for contributing. But I don't think that your framework is a good fit for this list yet. The framework has only been around for a couple weeks, it does not have a stable version, the documentation is incomplete, and there are multiple issues with responsiveness. Also note that your frameworks loads several custom fonts and is thus by far larger compared to the ~5kb of the other lightweight frameworks.

Feel free to create a pull request once you feel the framework is ready and there are people using it.
