### ISSUE TITLE
Add copy-and-paste libraries? (VueTailwind.com)

### ISSUE THREAD

**Issue by saleh-mir** [troxler/awesome-css-frameworks#53]
There are new kinds of libraries that host components but require no installation if the user already has Tailwind installed. 

I created https://VueTailwind.com which works this way. Please see if it fits in this repo. Here is the Github repository of it:
https://github.com/vuetailwind/components

**Comment by troxler** [comment]
Thanks for the suggestion. But that is not a framework and thus not a match for this list.
