### ISSUE TITLE
Add beercss

### ISSUE THREAD

**Issue by leonardorafael** [troxler/awesome-css-frameworks#62]
Can you add https://github.com/beercss/beercss ? 🙃

**Comment by troxler** [comment]
Thanks for the suggestion. Your framework looks like a good start, but does not yet meet the (quality) critieria to be added to this list.

* On certain screen sizes, there is horizontal scrolling.
* The demo site is unusable when the custom font fails to load. You don't even define any fallback fonts at all. And all the icons would be failing. That is especially concerning for the checkboxes and radioboxes.
* Your forms are not accessible as there is no focus styling on most elements.
* Setting a height to a table cell does not work with multi-line content. You should add spacing instead.
* Headings are non-semantic in the demo. There is no `h1` element and you use `<div class="h4">Thank you!</div>` for headings. You might want to use something like `<h1 class="h4">Heading</h1>` if your own styling does not fit the desired outcome.
* Beer css still seems very new. And judging from the number of GitHub stars and npm downloads, it is not used that often.

Feel free to reopen this issue when you think I should have another look.

**Comment by leonardorafael** [comment]
I'm back 🙃

Can you add https://github.com/beercss/beercss this time?
