### ISSUE TITLE
Suggestion: Skelet.css framework

### ISSUE THREAD

**Issue by thagxt** [troxler/awesome-css-frameworks#63]
I'd like to suggest our css framework called **Skelet.**

- Github repo: https://github.com/selekkt/skelet
- Docs/Demo: https://selekkt.dk/skelet/v3/

**Comment by troxler** [comment]
Thanks for the suggestion. Unfortunately, Skelet breaks several Web Standards and/or best-practices. You are using undefined custom elements (with [invalid names](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)) which should be avoided. And if you really want to use custom attributes, use the [standard `data-` attributes](https://html.spec.whatwg.org/#embedding-custom-non-visible-data-with-the-data-*-attributes) instead. Additionally, there are usability issues regarding focus. Some elements (e.g. links and buttons) don't have any focus styling at all while others (e.g. selected checkboxes, radio buttons, switches) are hardly distinguishable. And on medium-sizes screens, the font size is so small that it is completely illegible. Maybe [Fluid Typography with two-dimensional CSS Locks](https://frontaid.io/blog/fluid-typography-2d-css-locks-clamp/) might be helpful.

Skelet needs some more work before it can be considered for this list.
