### ISSUE TITLE
Add Bamboo CSS

### ISSUE THREAD

**Issue by rilwis** [troxler/awesome-css-frameworks#65]
Hi, I'd like to recommend [Bamboo CSS](https://github.com/rilwis/bamboo), a classless CSS library.

**Comment by troxler** [comment]
Thanks for the suggestion. I found a couple of issues:

* Multiple attribute selectors are broken, e.g. `[type="color" i]`
* Focus styling is inconsistent. I'm testing with Firefox and most interactive elements have a—hardly visible—dotted border. Except for checkboxes and radio buttons; they have both an outline and the dotted border. `details` does not have a focus styling at all.
* The dropdown is indistinguishable from an input field.
* And judging by the number of stars, your framework is not widely-used. Try to make it more popular.

**Comment by rilwis** [comment]
I added 2 fix for focus and dropdown styling.

`[type="color" i]` is not a multiple attribute selector. It's the [single attribute selector with case-insensitivity](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).

**Comment by troxler** [comment]
> single attribute selector with case-insensitivity

Thanks! Every day's a school day.

The updated focus styling is hardly visible on form elements. And don't forget about your dark mode where it is unusable on links and buttons.
