### ISSUE TITLE
demo for Tailwind CSS

### ISSUE THREAD

**Issue by thezoorat** [troxler/awesome-css-frameworks#68]
there is no official _demo_ or _showcase_ page for Tailwind CSS
but there is 3rd party site for that 
for example 

https://tailwindcomponents.com/
https://builtwithtailwind.com/
https://madewithtailwindcss.com/

can those be added ??

**Comment by troxler** [comment]
Thanks for the suggestion. I'd like to avoid third-party sites as that might encourage low-quality pull requests. I think that the respective frameworks should link to such resources, but not this list.
