### ISSUE TITLE
Metro UI should be included

### ISSUE THREAD

**Issue by Laisvunas** [troxler/awesome-css-frameworks#72]
Metro UI should be included

https://github.com/olton/Metro-UI-CSS

https://metroui.org.ua/

It now has 6800 stars on Github.

**Comment by troxler** [comment]
Duplicate of #30.

Metro has improveded slightly in regards of keyboard support. But some elements are hardly usable because their focus styling has barely any contrast. For example, selected checkboxes don't have any *visible* focus styling at all.
