### ISSUE TITLE
Add beercss

### ISSUE THREAD

**Issue by leonardorafael** [troxler/awesome-css-frameworks#75]
Trying again 🙃
Can you add beercss project this time?
Github: https://github.com/beercss/beercss
Page: https://www.beercss.com

![cover](https://user-images.githubusercontent.com/12979016/127204289-0773013b-a68b-4ced-a210-ecea725bf6ab.png)

Thank you!

**Comment by laurentpayot** [comment]
:100:

**Comment by troxler** [comment]
Hi. I had another look:

* The demo page is still completely unusable if the icon font family fails to load for some reason. They generally also have other problems, e.g. https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/
* Loading font families from a third-party contradicts "It has zero dependencies."
* Some components are not accessible with the keyboard, e.g. dropdowns, date pickers, modals, tabs.
* Inputs in the error state don't have a focus styling.
* Your demo page has a weird structure. The main heading is using `h4`, the others use `h5`. Semantically, that does not make any sense.
* I realize that you spent a lot of time improving the framework. But judging from Github stars and npm downloads,  unfortunately, it still has only a very small reach. Try to make it more popular ;)

**Comment by leonardorafael** [comment]
Ok, I'll back another time 😀
