### ISSUE TITLE
Add Rivet by Indiana university

### ISSUE THREAD

**Issue by Laisvunas** [troxler/awesome-css-frameworks#95]
Hi,

Rivet  by Indiana university might be added to the list of CSS frameworks:

https://rivet.iu.edu/

https://rivet.iu.edu/about/

**Comment by troxler** [comment]
Thanks for the suggestion. It seems that this specifically targets at projects related to IU. Neither GitHub stars nor npm downloads suggest that this design system is used that much. Hence, I don't think this is interesting for a broader audience.
